pipeline:
  backend:
    image: python:3.6
    environment:
      - PYTHONPATH=usr/local/lib/python3.6/site-packages
      - PATH=usr/local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    commands:
      - pip install --root . -r requirements.txt

  frontend:
    image: node
    commands:
      - ls usr/local/lib/python3.6/site-packages
      - npm install --quiet

  push:
    image: plugins/docker
    repo: weargoggles/drone-build-demo
    tags: latest
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
