pipeline:
  backend:
    image: python:3.6
    environment:
      - PYTHONPATH=usr/local/lib/python3.6/site-packages
      - PATH=usr/local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    commands:
      - pip install --root . -r requirements.txt
      - py.test tests.py

  frontend:
    image: node:6
    commands:
      - npm install --quiet
      - npm run build
      - npm run test

  push:
    image: plugins/docker
    repo: weargoggles/drone-build-demo
    tags: ${DRONE_TAG}
    secrets: [ docker_username, docker_password ]
    when:
      event: tag

  deploy:
    image: weargoggles/drone-nomad
    pull: true
    nomad_address: http://nomad-internal.gibbon.space
    configuration: nomad.hcl
